# Generated by Django 3.0.3 on 2020-06-02 09:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_subject', models.CharField(max_length=500)),
                ('sub_description', models.TextField()),
                ('subject', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('right_option', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('updated_time', models.DateTimeField(default=datetime.datetime(2020, 6, 2, 14, 48, 49, 256158))),
                ('subject_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='questions.Sub_subject')),
            ],
        ),
    ]
