# Generated by Django 3.0.3 on 2020-06-17 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20200617_1240'),
        ('questions', '0014_auto_20200606_1751'),
    ]

    operations = [
    ]
