# Generated by Django 3.0.6 on 2020-06-17 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0033_auto_20200617_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 19, 23, 29, 858439)),
        ),
    ]
