# Generated by Django 3.0.6 on 2020-06-17 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0038_auto_20200617_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 21, 6, 23, 209150)),
        ),
    ]
